### ISSUE TITLE
Usage of the Wire library.

### ISSUE THREAD

**Issue by Koepel** [MoJo2600/esp-soil-moisture-sensor#1]
In the file "esp-soil-moisture-sensor/src/esp-soil-moisture-sensor.cpp" in the function "getSendTemperature()" there is a `Wire.endTransmission()` after a `Wire.requestFrom()`.
That `Wire.endTransmission()` can be removed, it is at the moment at line 197.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

There is no need to use a while-loop. If two bytes are requested, then two bytes are available if there was no failure.

```
  // Request 2 bytes , Msb first to get temperature
  Wire.requestFrom(TMP_ADDR, 2);
  // Read temperature as Celsius (the default)
  if(Wire.available() == 2) {      // changed, while -> if == 2
    int msb = Wire.read();
    int lsb = Wire.read();
                                   // changed, removed Wire.endTransmission
    int rawtmp = msb << 8 | lsb;
    int value = rawtmp >> 4;
    temperature = value * 0.0625;
  }
```

**Comment by MoJo2600** [comment]
Nice! Thank you! I will change this, but you are very welcome to create a pull request as well!
